first = input("Enter first name: ")
last = input("Enter last name: ")
age = input ("Enter his age: ")
height = input("Enter his height: ")
print (first, last ," is a superhero. His age is", age,". His height is ", height)